version: '3'
services:
  jira-logger-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/jira-logger-api:prod
    container_name: jira-logger-api
    environment:
      - TZ=America/Denver
    ports:
      - "8080:5000"
    restart: unless-stopped
    user: "1435:1435" 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M